INHERIT: docs/mkdocs-base.yml

site_name: Computational Statistics
site_url: https://tschm.github.io/cs/
repo_url: https://github.com/tschm/cs
repo_name: tschm/cs

docs_dir: docs

nav:
  - Home: index.md
  - Development:
      - Marimo: development/MARIMO.md
  - Notebooks:
      - Experiment1: notebooks/Experiment1.html
      - Experiment2: notebooks/Experiment2.html
      - Experiment3: notebooks/Experiment3.html
      - Experiment4: notebooks/Experiment4.html
      - Experiment5: notebooks/Experiment5.html
