# This workflow builds and deploys marimo notebooks to GitHub Pages
# It runs automatically when changes are pushed to the main branch or can be triggered manually

name: MAINTENANCE

# Defines when the workflow will run
on:
  push

permissions:
  contents: 'read'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      # Run pre-commit checks using the cradle action
      - uses: tschm/cradle/actions/pre-commit@v0.1.72

  test:
    uses: jebel-quant/marimushka/.github/workflows/test.yml@v0.1.1
    with:
      notebook-dir: book/marimo
