# This file is part of the tschm/.config-templates repository
# (https://github.com/tschm/.config-templates).
#
# Workflow: Sync
# Purpose: This workflow synchronizes configuration files from the template repository
#          to other repositories, creating a pull request with the changes.
#
# Trigger: This workflow runs manually via workflow_dispatch
#
# Components:
#   - 📥 Checkout the target repository
#   - 🔄 Sync configuration templates
#   - 📝 Create a pull request with the changes

name: SYNC

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday at midnight

permissions:
  contents: write  # Needed to create releases

env:
  TEMPLATE_REPO: 'tschm/.config-templates'
  TEMPLATE_BRANCH: '77-action-with-explicit-devcontainer-copy'
  TARGET_BRANCH: 'sync/update'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the target repo
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0
          persist-credentials: 'false'

      - name: Sync Template
        id: sync
        uses: jebel-quant/sync_template@main
        with:
          token: ${{ secrets.PAT_TOKEN }}
          template-repository: ${{ env.TEMPLATE_REPO }}
          template-branch: ${{ env.TEMPLATE_BRANCH }}
          branch: ${{ env.TARGET_BRANCH }}
          commit-message: "chore: sync template files"
          include: |
            .github
            taskfiles
            tests
            .editorconfig
            .gitignore
            .pre-commit-config.yaml
            CODE_OF_CONDUCT.md
            CONTRIBUTING.md
            Makefile
            ruff.toml
            Taskfile.yml
