name: WASM

on:
  push

# Permissions needed for the workflow
permissions:
  contents: write  # Allows the workflow to write to the repository (create tags)

jobs:
  # Job to generate a new version tag
  html:
    runs-on: ubuntu-latest

    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.69

      - name: Export notebook via wasm
        run: |
          mkdir -p dist/wasm/ex1
          # export as readonly, with code locked
          marimo export html-wasm book/marimo/Experiment1.py -o dist/wasm/ex1 --mode run
