name: WASM

on:
  push

# Permissions needed for the workflow
permissions:
  contents: write  # Allows the workflow to write to the repository (create tags)

jobs:
  # Job to generate a new version tag
  html:
    runs-on: ubuntu-latest

    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.69

      - name: Export notebooks via wasm
        run: |
          # Find all Python files in book/marimo directory
          for notebook in book/marimo/Experiment*.py; do
            # Extract the filename without extension
            filename=$(basename "$notebook" .py)
            # Create output directory
            mkdir -p "dist/wasm/$filename"
            # Export as readonly, with code locked
            marimo export html-wasm "$notebook" -o "dist/wasm/$filename" --mode run
            echo "Exported $notebook to dist/wasm/$filename"
          done
